CREATE TABLE common.tags(
       id SERIAL PRIMARY KEY,
       tag VARCHAR(64) NOT NULL UNIQUE,
       ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
       mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);


CREATE TABLE common.comments(
       id SERIAL NOT NULL PRIMARY KEY,
       parent_id INTEGER REFERENCES common.comments(id) ON UPDATE CASCADE ON DELETE RESTRICT,
       content TEXT NOT NULL,
       deleted BOOLEAN DEFAULT FALSE,
       ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
       mtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS parent_idx ON common.comments(parent_id);
